apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "platops-please-work"
  description: "hello"
  annotations:
    # This must match folder-name/job-name in Jenkins.
    jenkins.io/job-full-name: cft:HMCTS_platops/please-work-9001
    github.com/project-slug: 'hmcts-test/please-work-9001'
  tags:
    - nodejs
  links:
    - url: https://hmcts-reform.slack.com/app_redirect?channel=cloud-native
      title: cloud-native on Slack
      icon: chat
spec:
  type: service
  system: platops
  lifecycle: experimental
  owner: dts_platform_operations
